apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-wait-app
  labels:
    app: simple-wait-app
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: simple-wait-app
  template:
    metadata:
      labels:
        app: simple-wait-app
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Waiting {{ .Values.startupDelay }} seconds before starting..."
          sleep {{ .Values.startupDelay }}
          nginx -g 'daemon off;'
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
