apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-install-app
  labels:
    app: post-install-app
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post-install-app
  template:
    metadata:
      labels:
        app: post-install-app
    spec:
      containers:
      - name: nginx
        image: {{ .Values.image }}
        ports:
        - containerPort: 80
        command: ["/bin/sh"]
        args:
        - -c
        - |
          echo "Post-install deployment starting..."
          echo "Main app should be ready now!"
          nginx -g 'daemon off;'
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 3
