apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: gitlab
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-gitlab:v0.13.0