apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep2
  labels:
    app: dep2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dep2
  template:
    metadata:
      labels:
        app: dep2
    spec:
      serviceAccountName: kubectl-waiter
      containers:
      - name: kubectl-waiter
        image: {{ .Values.dep2.image }}
{{- if .Values.dep2.useStartupProbe }}
        command: ["tail", "-f", "/dev/null"]
        startupProbe:
          exec:
            command:
            - sh
            - -c
            - |
              echo "Checking if dep1 deployment exists..."
              kubectl get deployment dep1 
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 1
          timeoutSeconds: 10
{{- else }}
        command: ["sh", "-c"]
        args:
        - |
          echo "Checking if dep1 deployment exists..."
          if kubectl get deployment dep1; then
            echo "dep1 deployment found! Starting main container..."
            # Keep container running
            tail -f /dev/null
          else
            echo "dep1 deployment not found, exiting..."
            exit 1
          fi
{{- end }}
