apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubectl-waiter
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubectl-waiter
  namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubectl-waiter
  namespace: default
subjects:
- kind: ServiceAccount
  name: kubectl-waiter
  namespace: default
roleRef:
  kind: Role
  name: kubectl-waiter
  apiGroup: rbac.authorization.k8s.io
