apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sync-waves-understand
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TehilaTheStudent/helm-charts.git
    targetRevision: main   # or another branch/tag/commit
    path: argocd-sync-waves-understand/helm-chart       # adjust if the chart is in a subfolder
    helm:
      parameters:
        - name: dep2.useStartupProbe
          value: "false"
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
